
[bundles]


[plugins]

aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
lbAndroidApplication = { id = "studio.lunabee.plugins.android.application", version.ref = "lbAndroidApplication" }
lbDetekt = { id = "studio.lunabee.plugins.detekt", version.ref = "lbDetekt" }
lbDokka = { id = "studio.lunabee.plugins.dokka", version.ref = "lbDokka" }
lbResources = { id = "studio.lunabee.plugins.resources", version.ref = "lbResources" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }

[versions]

aboutlibraries = "13.1.0"
android-gradle-plugin = "8.13.1"
android-tools-desugar_jdk_libs = "2.1.5"
androidx-activity = "1.12.1"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-autofill = "1.3.0"
androidx-benchmark = "1.4.1"
androidx-biometric = "1.1.0"
androidx-core = "1.17.0"
androidx-core-splashscreen = "1.2.0"
# FIXME 1.1.0 have some issue when cleaning and re-reading data (see export_engine_not_signed_up_test). To investigate
androidx-datastore = "1.0.0"
androidx-emoji2 = "1.6.0"
androidx-hilt = "1.3.0"
androidx-hilt-navigation-compose = "1.3.0"
androidx-lifecycle = "2.10.0"
androidx-media3 = "1.8.0"
androidx-paging = "3.3.6"
androidx-paging-compose = "3.3.2"
androidx-palette = "1.0.0"
androidx-preference = "1.2.1"
androidx-room = "2.8.4"
androidx-security-crypto = "1.1.0"
androidx-slice-builders-ktx = "1.0.0-alpha08"
androidx-sqlite = "2.6.2"
androidx-startup = "1.2.0"
androidx-test-core = "1.7.0"
androidx-test-ext-junit = "1.3.0"
androidx-test-rules = "1.7.0"
androidx-test-runner = "1.7.0"
androidx-test-uiautomator = "2.3.0"
androidx-tracing = "1.3.0"
androidx-work = "2.11.0"
bouncycastle = "1.83"
bouquet = "1.1.3"
camerax = "1.5.2"
coil-kt = "2.7.0"
compose-bom-alpha = "2024.02.00-alpha02"
compose-bom-stable = "2025.12.00"
compose-shimmer = "1.3.3"
conscrypt = "2.5.3"
conscrypt-openjdk-uber = "2.5.2"
crashkios = "0.9.0"
dagger-hilt = "2.57.2"
doubleratchet = "1.1.1"
espresso-core = "3.7.0"
exifinterface = "1.4.2"
firebase-bom = "34.6.0"
firebase-crashlytics-gradle = "3.0.6"
florisboard-library = "0.5.1-1.0.6"
glance = "1.1.1"
google-accompanist = "0.37.3"
google-android-material = "1.13.0"
google-api-client = "2.8.1"
google-api-services-drive = "v3-rev20251114-2.0.0"
google-services = "4.4.4"
javapoet = "1.13.0"
javax-inject = "1"
junit-jupiter = "5.11.4"
junit4 = "4.13.2"
koin = "4.1.1"
kotlin = "2.2.21"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
ksp = "2.3.3"
ktor = "3.3.3"
lbAndroidApplication = "1.1.0"
lbDetekt = "2.0.2"
lbDokka = "1.0.0"
lbResources = "1.1.0"
lbcaccessibility = "1.13.0"
lbcandroidtest = "1.14.0"
lbccore = "1.11.0"
lbcglance = "1.5.0"
lbchaptic = "1.7.0"
lbctheme = "1.9.0"
lint = "31.13.1"
logback-classic = "1.5.21"
lottie = "6.7.1"
lunabee-library = "4.7.0"
mockk = "1.14.7"
navigation-compose = "2.9.6"
nbvcxz = "1.5.1"
play-services-auth-base = "18.3.0"
play-services-base = "18.9.0"
process-phoenix = "3.0.0"
protobuf = "4.33.2"
protobuf-plugin = "0.9.5"
review = "2.0.2"
robolectric = "4.16"
seismic = "1.0.3"
skie = "0.10.8"
skydoves-colorpicker = "1.1.3"
slf4j-simple = "2.0.17"
sqlcipher-android = "4.11.0"
threeten-extra = "1.8.0"
tink-android = "1.19.0"
zoomable = "2.9.0"
zxing-android-embedded = "4.3.0"

[libraries]

aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "google-accompanist" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "google-android-material" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
androidx-media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidx-media3" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
autofill = { group = "androidx.autofill", name = "autofill", version.ref = "androidx-autofill" }
benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "androidx-benchmark" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidx-biometric" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
bouquet = { group = "io.github.grizzi91", name = "bouquet", version.ref = "bouquet" }
camerax-camera = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camerax-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "camerax" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-kt" }
#noinspection SimilarGradleDependency
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom-stable" }
compose-bom-alpha = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "compose-bom-alpha" }
#noinspection SimilarGradleDependency
compose-bom-stable = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom-stable" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "compose-shimmer" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
conscrypt-android = { group = "org.conscrypt", name = "conscrypt-android", version.ref = "conscrypt" }
conscrypt-openjdk-uber = { group = "org.conscrypt", name = "conscrypt-openjdk-uber", version.ref = "conscrypt-openjdk-uber" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
crashkios = { group = "co.touchlab.crashkios", name = "crashlytics", version.ref = "crashkios" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidx-datastore" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-tools-desugar_jdk_libs" }
doubleratchet = { group = "studio.lunabee.doubleratchet", name = "doubleratchet", version.ref = "doubleratchet" }
emoji2 = { group = "androidx.emoji2", name = "emoji2", version.ref = "androidx-emoji2" }
emoji2-bundled = { group = "androidx.emoji2", name = "emoji2-bundled", version.ref = "androidx-emoji2" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
florisboard = { group = "studio.lunabee.florisboard", name = "florisboard-library", version.ref = "florisboard-library" }
glance-widget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version.ref = "google-api-client" }
google-api-services-drive = { group = "com.google.apis", name = "google-api-services-drive", version.ref = "google-api-services-drive" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger-hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax-inject" }
journeyappszxing = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxing-android-embedded" }
# KMP
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }
kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
lbcaccessibility = { group = "studio.lunabee.compose", name = "lbcaccessibility", version.ref = "lbcaccessibility" }
lbcandroidtest = { group = "studio.lunabee.compose", name = "lbcandroidtest", version.ref = "lbcandroidtest" }
lbccore = { group = "studio.lunabee.compose", name = "lbccore", version.ref = "lbccore" }
lbcglance = { group = "studio.lunabee.compose", name = "lbcglance", version.ref = "lbcglance" }
lbchaptic = { group = "studio.lunabee.compose", name = "lbchaptic", version.ref = "lbchaptic" }
lbcore = { group = "studio.lunabee", name = "lbcore" }
lbcore-compose = { group = "studio.lunabee", name = "lbcore-compose" }
lbctheme = { group = "studio.lunabee.compose", name = "lbctheme", version.ref = "lbctheme" }
lbextensions = { group = "studio.lunabee", name = "lbextensions" }
lbextensions-android = { group = "studio.lunabee", name = "lbextensions-android" }
lbloading-hilt = { group = "studio.lunabee", name = "lbloading-hilt" }
lblogger = { group = "studio.lunabee", name = "lblogger-kermit" }
lblogger-crashlytics = { group = "studio.lunabee", name = "lblogger-kermit-crashlytics" }
lifecycle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "lint" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
lunabee-bom = { group = "studio.lunabee", name = "lunabee-bom", version.ref = "lunabee-library" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
nbvcxz = { group = "me.gosimple", name = "nbvcxz", version.ref = "nbvcxz" }
paging-common-ktx = { group = "androidx.paging", name = "paging-common-ktx", version.ref = "androidx-paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "androidx-palette" }
play-services-auth-base = { group = "com.google.android.gms", name = "play-services-auth-base", version.ref = "play-services-auth-base" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "play-services-base" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
process-phoenix = { group = "com.jakewharton", name = "process-phoenix", version.ref = "process-phoenix" }
protobuf-kotlinlite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
# Used in gradle protobuf block
protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
review = { group = "com.google.android.play", name = "review", version.ref = "review" }
review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "review" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidx-room" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "androidx-security-crypto" }
seismic = { group = "com.squareup", name = "seismic", version.ref = "seismic" }
skydoves-colorpicker = { group = "com.github.skydoves", name = "colorpicker-compose", version.ref = "skydoves-colorpicker" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j-simple" }
slice-builders-ktx = { group = "androidx.slice", name = "slice-builders-ktx", version.ref = "androidx-slice-builders-ktx" }
sqlcipher-android = { group = "net.zetetic", name = "sqlcipher-android", version.ref = "sqlcipher-android" }
sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "androidx-sqlite" }
startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }
threeten-extra = { group = "org.threeten", name = "threeten-extra", version.ref = "threeten-extra" }
tink-android = { group = "com.google.crypto.tink", name = "tink-android", version.ref = "tink-android" }
tracing = { group = "androidx.tracing", name = "tracing", version.ref = "androidx-tracing" }
work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidx-work" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }
